// Static server for the production build, used by `yarn start` (which is
// what supervisor runs on port 3000 in this environment).
//
// Why a custom server instead of `sirv` or `serve`:
//   * we need different Cache-Control headers for HTML vs hashed assets
//   * we want on-the-fly gzip + brotli for clients that didn't get a
//     precompiled sibling
//   * we want explicit headers (X-Content-Type-Options, Referrer-Policy)
//     so Lighthouse "Best Practices" scores 100.
//
// CRA filenames in /static/* contain a content hash, so they are safe to
// cache for a year and marked `immutable`. index.html is the one file
// that must never be cached (the backend rewrites the hero preload tag
// into it on every hero change).

const express = require("express");
const compression = require("compression");
const path = require("path");
const fs = require("fs");

const PORT = parseInt(process.env.PORT || "3000", 10);
const HOST = process.env.HOST || "0.0.0.0";
const BUILD = path.join(__dirname, "build");

if (!fs.existsSync(path.join(BUILD, "index.html"))) {
  console.error(`[server] No build/index.html found at ${BUILD}. Run \`yarn build\` first.`);
  process.exit(1);
}

const app = express();
app.disable("x-powered-by");

// On-the-fly gzip/brotli for everything we haven't precompiled.
app.use(compression({ level: 6, threshold: 1024 }));

// Security + performance headers across the board.
app.use((_req, res, next) => {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  res.setHeader("X-Frame-Options", "SAMEORIGIN");
  next();
});

// Hashed static assets: immutable for 1 year. Browsers will hold them in
// disk cache and never re-validate on subsequent navigations, which is
// what gets us to "Use efficient cache lifetimes" pass.
app.use(
  "/static",
  express.static(path.join(BUILD, "static"), {
    fallthrough: false,
    maxAge: "365d",
    immutable: true,
    setHeaders(res) {
      res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
    },
  }),
);

// Public /assets/* directory: site logos, favicons, OG cards, audio etc.
// All of these are deployed alongside the JS bundle and only change when
// the source repo changes, so 1-year immutable is safe. This was the
// missing piece for Lighthouse's "Use efficient cache lifetimes" pass.
app.use(
  "/assets",
  express.static(path.join(BUILD, "assets"), {
    fallthrough: false,
    maxAge: "365d",
    immutable: true,
    setHeaders(res) {
      res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
    },
  }),
);

// llms.txt and llms-full.txt are regenerated by the backend on every
// content save (see regenerate_llm_feeds in server.py). They sit in
// build/ at startup but should not be aggressively cached.
app.get(["/llms.txt", "/llms-full.txt", "/robots.txt", "/sitemap.xml"], (req, res, next) => {
  res.setHeader("Cache-Control", "public, max-age=300, must-revalidate");
  next();
});

// Everything else from /build (manifest.json, miscellaneous root files)
// gets a moderate cache. Most filenames here are content-addressable
// thanks to CRA's build pipeline; index.html is the one exception (the
// backend rewrites HERO_PRELOAD markers in it on every hero change).
app.use(
  express.static(BUILD, {
    fallthrough: true,
    maxAge: "1d",
    setHeaders(res, filePath) {
      if (filePath.endsWith("index.html")) {
        res.setHeader("Cache-Control", "no-store, must-revalidate");
      } else if (/\.(woff2?|ttf|otf)$/i.test(filePath)) {
        // Fonts (if any are self-hosted) are perfectly cacheable.
        res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
      }
    },
  }),
);

// SPA fallback — every unmatched route renders index.html.
app.get("*", (_req, res) => {
  res.setHeader("Cache-Control", "no-store, must-revalidate");
  res.sendFile(path.join(BUILD, "index.html"));
});

app.listen(PORT, HOST, () => {
  console.log(`[server] Once Were Wild static server listening on http://${HOST}:${PORT}`);
});
